### PR TITLE
Us40 sidebar icons

### PR DESCRIPTION
**Pull request by preston-goulet**
What does this implement/fix? Explain your changes.
---------------------------------------------------
US40. Changes icons
Does this close any currently open issues?
------------------------------------------
No
Any relevant logs, error output, etc?
-------------------------------------
NA
Include screenshots of Memoranda with your fixes
------------------------------------------------
screen shot 2018-02-17 at 12 58 24 pm

Any other comments?
-------------------
…

### CODE REVIEW

**Comment by cboulte1** [comment]
Before merging, please take a look at the following and let me know if there's any fix for the highlighting inconsistencies. You'll see different white space for different icons. Might have to do with the files being cut out differently.

screen shot 2018-02-19 at 1 13 23 am

screen shot 2018-02-19 at 1 13 31 am

**Comment by cboulte1** [comment]
The tasks one looks good. Can we streamline that consistent blue look around the icon throughout?

**Comment by preston-goulet** [comment]
Changes have been made. All of the icons on the sidebar should highlight the same now.

**Comment by cboulte1** [comment]
Looks good. Checked all tab highlighting, and reviewed code to confirm it adhered to style standards.

**Pull request merged**
