### PR TITLE
[100%] Adds dock icon for Windows & Mac

### PR DESCRIPTION
**Pull request by preston-goulet**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Comments where the code is for changing the dock image &
Changes dock image for Windows platform. Still incomplete for Mac.

Does this close any currently open issues?
------------------------------------------
No. Incomplete

Any relevant logs, error output, etc?
-------------------------------------
No

Include screenshots of Memoranda with your fixes
------------------------------------------------
NA

Any other comments?
-------------------
Needs to be tested by someone on Windows to ensure that the dock icon really works and is the new icon and not the Java default icon.

### CODE REVIEW

**Comment by preston-goulet** [comment]
The build failed because it looks like the Mac OS X package that comes with java for mac won't be in the Windows JRE and will therefore probably not be able to run on a windows computer. I'm looking up how to install a plugin or something on widows computers so they will recognize the com.apple.eawt package. But test anyway and let me know if it will work

**Comment by preston-goulet** [comment]
Should be ready to test now. Just make sure that the dock icon has been changed on Windows computers.

**Comment by jcpowel5** [comment]
screen shot 2018-02-22 at 1 17 21 pm
Mac Icon

**Comment by jcpowel5** [comment]
Mac Bug: Program still won't reopen once minimized. Don't know if this bug is for this user story though as the user only specified icons.

**Pull request merged**
